accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'
urlpatterns = [

    path('login', login_view, name='login'),
    path('register', register_view, name='register'),
    path('logout', logout_view, name='logout'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include("todo.urls")),
    path('accounts/', include("accounts.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from .views import *

app_name = 'todo'
urlpatterns = [
    path('', list_view, name='list'),
    path('create/', create_view, name='create'),
    path('delete<slug>/', delete_view, name='delete'),
    path('update<slug>/', update_view, name='update'),
]

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from services.mixin import DateMixin, SlugMixin
from services.uploader import Uploader
from services.generator import Generator

User = get_user_model()


class Profile(DateMixin, SlugMixin):
    user = models.OneToOneField(User, on_delete=models.CASCADE, )
    birthday = models.DateTimeField(null=True, blank=True)
    avatar = models.ImageField(upload_to=Uploader.upload_images_to_profile, null=True, blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ("-created_at",)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = Generator.create_slug_shortcode(size=15, model_=Profile)
        super(Profile, self).save(*args, **kwargs)

todo/models.py
from django.db import models
from services.mixin import DateMixin, SlugMixin
from services.choices import TODO_STATUS
from services.generator import Generator
from django.contrib.auth import get_user_model
User = get_user_model()


class Todo(DateMixin, SlugMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    task_name = models.CharField(max_length=200)
    deadline = models.DateField()
    status = models.CharField(max_length=100, choices=TODO_STATUS, default='Uncompleted')

    def __str__(self):
        return self.task_name

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Todo'
        verbose_name_plural = 'Todo'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = Generator.create_slug_shortcode(size=15, model_=Todo)
        super(Todo, self).save(*args, **kwargs)

accounts/forms.py
from django import forms
from .models import User


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={"type": "password"}))

    class Meta:
        model = User
        fields = ("username", "password",)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError("This user doesn't exist")
        else:
            user = User.objects.get(username=username)

            if not user.is_active:
                raise forms.ValidationError('User is not activated')
            if not user.check_password(password):
                raise forms.ValidationError("Password is wrong")
        return self.cleaned_data

todo/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):
    deadline = forms.CharField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Todo
        fields = ('task_name', 'deadline',)

    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

accounts/views.py
from django.shortcuts import render, redirect
from .models import User, Profile
from django.contrib.auth import login, logout
from .forms import LoginForm


def login_view(request):
    context = {}
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request.POST or None)
        if form.is_valid():
            user = User.objects.get(username=form.cleaned_data.get("username"))
            login(request, user)
            return redirect("todo:list")
    context['form'] = form
    return render(request, 'login.html', context)


def register_view(request):
    context = {}
    if request.method == "POST":
        user = User.objects.create(
            first_name=request.POST.get('name'),
            last_name=request.POST.get('surname'),
            username=request.POST.get('username'),

        )
        user.set_password(request.POST.get("password"))
        user.save()
        login(request, user)
        return redirect("accounts:register")

    return render(request, 'register.html', context)


def logout_view(request):
    logout(request)
    return redirect('accounts:login')

todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Todo, User
from django.db.models import Case, When, Value, CharField, Q
from django.contrib import messages
from .forms import TodoForm


def list_view(request):
    user = request.user
    todo_list = Todo.objects.filter(user=user).annotate(

        status_value=Case(
            When(status="Completed", then=Value('checked')),
            default=Value(""),
            output_field=CharField()
        )

    ).order_by('-created_at')

    status = request.GET.get('status', None)
    start_date = request.GET.get('start_date', None)
    end_date = request.GET.get('end_date', None)

    filter_ = Q()

    if status and status != "All":
        filter_.add(Q(status=status), Q.AND)
    if start_date:
        filter_.add(Q(deadline__gte=start_date), Q.AND)
    if end_date:
        filter_.add(Q(deadline__lt=end_date), Q.AND)

    todo_list = todo_list.filter(filter_)

    context = {
        'todo_list': todo_list
    }
    return render(request, 'list.html', context)


def delete_view(request, slug):
    todo = get_object_or_404(Todo, slug=slug)
    messages.success(request, f"{todo.task_name} is deleted !")
    todo.delete()
    return redirect("todo:list")


def create_view(request):
    context = {}
    form = TodoForm()

    if request.method == 'POST':
        form = TodoForm(request.POST or None)
        if form.is_valid():
            data = form.save()
            messages.success(request, f"\"{data.task_name}\"  is successfully created!")
            return redirect("todo:list")

    context['form'] = form
    return render(request, 'create.html', context)


def update_view(request, slug):

    todo = get_object_or_404(Todo, slug=slug)
    context = {}
    form = TodoForm(instance=todo)
    if request.method == "POST":
        form = TodoForm(request.POST or None, instance=todo)
        if form.is_valid():
            obj = form.save()
            if "check" in request.POST:
                obj.status = "Completed"
                obj.save()
            return redirect("todo:list")
    context['form'] = form
    return render(request, 'create.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %} {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'todo:list' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:create' %}">Create Page</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login Page</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">Register Page</a>
        </li>
      </ul>
{% if request.user.is_authenticated %}
       <li class="nav-item btn btn-danger">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
{% endif %}
    </div>
  </div>
</nav>

  {% block body %}

  {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

templates/create.html
{% extends 'base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{% block title %}    <title>Todo Create Page</title>  {% endblock %}
</head>

<body>


{% block body %}

<div class="container mt-5">

    <h1>Todo List</h1>

    {% if messages %}
        {% for message in messages %}

        <div class="alert alert-{{ message.tags }}" role="alert">

          {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    {% if form.errors %}
                                        <div class="error-message mb-4">
                                                {% for field in form %}
                                                    {% for error in field.errors %}
                                                        <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                    {% endfor %}
                                                {% endfor %}
                                                {% for error in form.non_field_errors %}
                                                    <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                {% endfor %}
                                        </div>
                                {% endif %}



</div>

<div class="container mt-5">


    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
        <label>{{field.label}}</label>
        {{field}}



        {% endfor %}
        <div class="row">
            Status: <input type="checkbox" name="check">
        </div>
        <button type="submit" class="btn btn-success mt-3">Submit</button>

    </form>



</div>



{% endblock %}



</body>
</html>

templates/list.html
{% extends 'base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{% block title %}    <title>Todo List Page</title>  {% endblock %}
</head>

<body>



{% block body %}
<div class="center">
    Welcome {{request.user.username}}
</div>
<div class="container mt-5">

    <h1>Todo List</h1>

    {% if messages %}
        {% for message in messages %}

        <div class="alert alert-{{ message.tags }}" role="alert">

          {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    {% if form.errors %}
                                        <div class="error-message mb-4">
                                                {% for field in form %}
                                                    {% for error in field.errors %}
                                                        <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                    {% endfor %}
                                                {% endfor %}
                                                {% for error in form.non_field_errors %}
                                                    <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                {% endfor %}
                                        </div>
                                {% endif %}



</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-3 col-sm-12">
            <h3>Filter: </h3>
            <form>
                <div class="form-group mb-3">
                    <label class="mb-2">Status: </label> <br>
                    <input type="radio" name="status" value="All"> All <br>
                    <input type="radio" name="status" value="Completed"> Completed <br>
                    <input type="radio" name="status" value="Uncompleted"> Uncompleted<br>
                </div>
                <div class="form-group mb-3">
                    <label>Start date: </label> <br>
                    <input type="date" name="start_date" id="start_date" class="form-control"> <br>
                    <label>End date: </label> <br>
                    <input type="date" name="end_date" id="end_date" class="form-control">
                </div>

                <button type="submit" class="btn btn-success">Search..</button>

            </form>
        </div>
        <div class="col-md-9 col-sm-12">
            <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Deadline</th>
      <th scope="col">Status</th>
        <th></th>
        <th></th>
    </tr>
  </thead>
  <tbody>

  {% for todo in todo_list %}

    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{todo.task_name}}</td>
      <td>{{todo.deadline|date:"d.m.Y"}}</td>
      <td>
          <input type="checkbox" {{todo.status_value}}>
      </td>
        <td>
            <a href="{% url 'todo:delete' todo.slug %}" class="text-danger">Delete</a>
        </td>
                <td>
            <a href="{% url 'todo:update' todo.slug %}" class="text-primary">Update</a>
        </td>
    </tr>
  {% endfor %}

  </tbody>
</table>
        </div>
    </div>



</div>



{% endblock %}



</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{% block title %}    <title>Todo List Page</title>  {% endblock %}
</head>

<body>



{% block body %}

<div class="container mt-5">

    <h1>Todo List</h1>

    {% if messages %}
        {% for message in messages %}

        <div class="alert alert-{{ message.tags }}" role="alert">

          {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    {% if form.errors %}
                                        <div class="error-message mb-4">
                                                {% for field in form %}
                                                    {% for error in field.errors %}
                                                        <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                    {% endfor %}
                                                {% endfor %}
                                                {% for error in form.non_field_errors %}
                                                    <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                {% endfor %}
                                        </div>
                                {% endif %}



</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-3 col-sm-12">
         <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
{% for field in form %}
  <div class="form-group">
    <label>{{field.label}}:</label>
      {{field}}
  </div>
{% endfor %}


  <button type="submit" class="btn btn-success">Sign in</button>
</form>
        </div>
        <div class="col-md-9 col-sm-12">

        </div>
    </div>



</div>



{% endblock %}



</body>
</html>

templates/register.html
{% extends 'base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{% block title %}    <title>Todo List Page</title>  {% endblock %}
</head>

<body>



{% block body %}

<div class="container mt-5">

    <h1>Todo List</h1>

    {% if messages %}
        {% for message in messages %}

        <div class="alert alert-{{ message.tags }}" role="alert">

          {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    {% if form.errors %}
                                        <div class="error-message mb-4">
                                                {% for field in form %}
                                                    {% for error in field.errors %}
                                                        <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                    {% endfor %}
                                                {% endfor %}
                                                {% for error in form.non_field_errors %}
                                                    <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                {% endfor %}
                                        </div>
                                {% endif %}



</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-3 col-sm-12">
         <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label>Name: </label>
    <input type="text" name="name" class="form-control">
  </div>
  <div class="form-group">
    <label>Surname: </label>
    <input type="text" name="surname" class="form-control">
  </div>


  <div class="form-group">
    <label>Username: </label>
    <input type="text" name="username" class="form-control">
  </div>
  <div class="form-group">
    <label>Password: </label>
    <input type="password" name="password" class="form-control">
  </div>
     <div class="form-group">
    <label>Re-type password: </label>
    <input type="password" name="password" class="form-control">
  </div>


  <button type="submit" class="btn btn-success">Sign-up</button>
</form>
        </div>
        <div class="col-md-9 col-sm-12">

        </div>
    </div>



</div>



{% endblock %}



</body>
</html>